export const siteConfig = {
  name: "Umair",
  title: "Creative Strategy & Digital Growth Architect",
  description:
    "Creative strategist working at the intersection of storytelling, digital growth, and brand positioning. Led campaigns and content ecosystems across fashion, hospitality, healthcare, and corporate sectors generating millions of organic views and measurable brand growth.",
  email: "umairaziz085@gmail.com",
  social: {
    instagram: "https://instagram.com",
    linkedin: "https://linkedin.com",
    twitter: "https://twitter.com",
  },
};

const CL = "https://res.cloudinary.com/dgsjtycgd/image/upload/f_auto,q_auto,w_300";

export const brands = [
  // Fashion & Apparel
  { name: "Klay",           slug: "klay",           sector: "Fashion",    logo: `${CL}/klay-logo_bfslag` },
  { name: "Manas",          slug: "manas",          sector: "Fashion",    logo: `${CL}/manas-logo_v0m7jr` },
  { name: "Sulafah",        slug: "sulafah",        sector: "Fashion",    logo: `${CL}/sulafah-logo_yl9y8e` },
  { name: "Zubair Shah",    slug: "zubair-shah",    sector: "Fashion",    logo: `${CL}/Zubair_Shah-logo_odyckn` },
  { name: "Shahid Afridi",  slug: "shahid-afridi",  sector: "Fashion",    logo: "/shahidafridi-store-logo.webp" },
  { name: "AFM",            slug: "afm",            sector: "Fashion",    logo: `${CL}/afm-logo_hnnbju`,            fullName: "Artistic Fabric Mills" },
  { name: "Coach",          slug: "coach",          sector: "Fashion",    logo: `${CL}/coach-logo_bgrkxk` },
  { name: "Stylo",          slug: "stylo",          sector: "Fashion",    logo: `${CL}/Stylo-logo_aoqdtq` },
  { name: "Rizwan Beyg",    slug: "rizwan-beyg",    sector: "Fashion",    logo: `${CL}/Rizwanbeyg-logo_oxdpg1` },
  { name: "Aristovie",      slug: "aristovie",      sector: "Fashion",    logo: `${CL}/aristovie-logo_bvmhdf` },
  { name: "Princess Polly", slug: "princess-polly", sector: "Fashion",    logo: `${CL}/princesspolly-logo_t9bohz` },
  { name: "Zellbury",       slug: "zellbury",       sector: "Fashion",    logo: `${CL}/Zellbury-logo_jdny0c` },
  { name: "Kyousf",         slug: "kyousf",         sector: "Fashion",    logo: `${CL}/kyousuf-logo_ve65wh` },
  { name: "Icy",            slug: "icy",            sector: "Fashion",    logo: "/icy-logo.webp" },
  { name: "Burj",           slug: "burj",           sector: "Fashion",    logo: `${CL}/Burj-logo_lwfjin` },
  { name: "Tapestry",       slug: "tapestry",       sector: "Fashion",    logo: `${CL}/Tapestry-Logo_eklhls` },
  { name: "Kate Spade NY",  slug: "kate-spade",     sector: "Fashion",    logo: `${CL}/Kate_Spade-NY-Logo_rs7rtr` },
  // F&B / Hospitality
  { name: "Espresso",       slug: "espresso",       sector: "F&B",        logo: "/espresso-logo.avif" },
  { name: "Chatterbox",     slug: "chatterbox",     sector: "F&B",        logo: `${CL}/Chatterbox-logo_qxylct` },
  { name: "Pie in the Sky", slug: "pits",           sector: "F&B",        logo: `${CL}/pieinthesky-logo_bt1osw`,    fullName: "PITS" },
  { name: "Lucky Foods",    slug: "lucky-foods",    sector: "F&B",        logo: `${CL}/lucky-logo_i80y4c` },
  // Healthcare & Pharma
  { name: "Dr Seema",       slug: "dr-seema",       sector: "Healthcare", logo: `${CL}/Dr.SeemaSH-logo_fsdb39` },
  { name: "Abbott",         slug: "abbott",         sector: "Healthcare", logo: `${CL}/abbott-logo_fxa7te` },
  { name: "Searle",         slug: "searle",         sector: "Healthcare", logo: "/searle-logo-1.png" },
  { name: "BMJ",            slug: "bmj",            sector: "Healthcare", logo: `${CL}/bmj-logo_ykpxoj` },
  { name: "Elsevier",       slug: "elsevier",       sector: "Healthcare", logo: `${CL}/Elsevier-logo_gglsyd` },
  { name: "UpToDate",       slug: "uptodate",       sector: "Healthcare", logo: `${CL}/Uptodate-logo_lgfwos` },
  { name: "SAS",            slug: "sas",            sector: "Healthcare", logo: `${CL}/SAS-logo_sngbyq` },
  // Media & Publishing
  { name: "Dawn",           slug: "dawn",           sector: "Media",      logo: `${CL}/dawn-logo_nmbzjt` },
  { name: "Images",         slug: "images",         sector: "Media",      logo: `${CL}/images-logo_xmnnw4` },
  { name: "KCCI",           slug: "kcci",           sector: "Media",      logo: `${CL}/KCC-logo_i2e2h0` },
  { name: "Fashion As F",   slug: "fashion-as-f",   sector: "Media",      logo: `${CL}/FashionAsF-logo_nqnmfb` },
  // Arts & Culture
  { name: "Canvas Gallery", slug: "canvas",         sector: "Arts",       logo: "/canvas-galley-logo.jpg" },
  { name: "Arts Council",   slug: "arts",           sector: "Arts",       logo: "/arts-logo.png" },
  // Corporate & Business
  { name: "Delphi",         slug: "delphi",         sector: "Corporate",  logo: `${CL}/Delphi-logo_jfjzwi` },
  { name: "MGAT",           slug: "mgat",           sector: "Corporate",  logo: "/mgat-logo.png" },
  { name: "AVS",            slug: "avs",            sector: "Corporate",  logo: `${CL}/AVS-logo_zpedka` },
  { name: "Kupgrade",       slug: "kupgrade",       sector: "Corporate",  logo: "/Kupgrade-logo.png" },
  { name: "Layers",         slug: "layers",         sector: "Corporate",  logo: "/Layers-Logo.png" },
  { name: "Adamjee",        slug: "adamjee",        sector: "Corporate",  logo: `${CL}/adamjee-logo_gan0oo` },
  { name: "Gsthering",      slug: "gsthering",      sector: "Corporate",  logo: `${CL}/gathering-logo_rtsmmn` },
];

export const metrics = [
  {
    value: "5.2M+",
    label: "Organic Views",
    brand: "Espresso",
    description: "Multi-platform content ecosystem driving consistent organic discovery",
  },
  {
    value: "3.9M+",
    label: "Viral Campaign",
    brand: "Chatterbox",
    description: "Narrative-driven campaign that captured cultural conversation",
  },
  {
    value: "3.3M+",
    label: "Organic Reach",
    brand: "Fabio Magazine",
    description: "Editorial strategy positioning Fabio as a digital-first publication",
  },
  {
    value: "150K+",
    label: "Campaign Reach",
    brand: "Delphi",
    description: "Targeted growth campaign with precision audience development",
  },
  {
    value: "31K+",
    label: "Audience Growth",
    brand: "Shahid Afridi Store",
    description: "Community-first approach building a loyal brand audience",
  },
  {
    value: "2K+",
    label: "Monthly Comments",
    brand: "Fabio Magazine",
    description: "Engagement-first content strategy fostering active community",
  },
];

export const services = [
  {
    title: "Creative Strategy",
    description:
      "Building narrative frameworks that give brands a distinct voice and consistent creative direction across all touchpoints.",
    icon: "◈",
    tags: ["Brand Voice", "Narrative Frameworks", "Creative Direction"],
  },
  {
    title: "Content Systems",
    description:
      "Designing scalable content ecosystems that produce consistent, high-quality output without sacrificing creative integrity.",
    icon: "◉",
    tags: ["Content Architecture", "Editorial Planning", "Production Systems"],
  },
  {
    title: "Social Media Growth",
    description:
      "Data-informed growth strategies that build genuine audiences and convert attention into measurable brand equity.",
    icon: "◎",
    tags: ["Audience Development", "Platform Strategy", "Analytics"],
  },
  {
    title: "Campaign Architecture",
    description:
      "End-to-end campaign design from concept to execution — building campaigns that drive cultural conversation.",
    icon: "◇",
    tags: ["Campaign Strategy", "Cross-Platform", "Launch Planning"],
  },
  {
    title: "Short-Form Video Direction",
    description:
      "Directing and producing short-form video content that captures attention in the first three seconds and holds it.",
    icon: "◈",
    tags: ["Reels / TikTok", "Scripting", "Visual Direction"],
  },
  {
    title: "Brand Positioning",
    description:
      "Defining where a brand sits in the market and how it speaks — creating positioning that's both distinctive and defensible.",
    icon: "◉",
    tags: ["Market Positioning", "Brand Identity", "Competitive Analysis"],
  },
];

export interface CaseStudy {
  slug: string;
  brand: string;
  title: string;
  tagline: string;
  sector: string;
  year: string;
  challenge: string;
  strategy: string;
  execution: string;
  results: string;
  metrics: { value: string; label: string }[];
  tags: string[];
  featured: boolean;
  color: string;
}

export const caseStudies: CaseStudy[] = [
  {
    slug: "espresso-growth",
    brand: "Espresso",
    title: "Building a 5.2M View Content Ecosystem",
    tagline: "From café to cultural institution through strategic content.",
    sector: "Hospitality / Lifestyle",
    year: "2023",
    challenge:
      "Espresso had an established physical presence but lacked digital authority. Despite being a beloved local brand, their social content felt disconnected — product shots with little narrative, no consistent voice, and zero community engagement strategy.",
    strategy:
      "We repositioned Espresso from a café to a lifestyle destination. The strategy centered on three content pillars: atmosphere storytelling, community moments, and product craftsmanship. Each pillar had its own visual language, allowing the brand to be both consistent and varied.",
    execution:
      "We built a 90-day content calendar with weekly hero content, daily micro-content, and monthly campaign activations. Short-form video was prioritized — Reels and TikTok with cinematic production values that made every frame feel intentional. We introduced 'morning ritual' content that placed the brand inside the viewer's daily narrative.",
    results:
      "In 8 months, Espresso's content generated over 5.2M organic views across platforms. Engagement rate increased by 340%. The brand became a reference point for hospitality content in the region.",
    metrics: [
      { value: "5.2M+", label: "Organic Views" },
      { value: "340%", label: "Engagement Increase" },
      { value: "8", label: "Months to Result" },
      { value: "3", label: "Content Pillars" },
    ],
    tags: ["Content Strategy", "Social Growth", "Short-Form Video", "Hospitality"],
    featured: true,
    color: "#c9a96e",
  },
  {
    slug: "chatterbox-campaign",
    brand: "Chatterbox",
    title: "The 3.9M View Viral Campaign",
    tagline: "Turning a product launch into a cultural conversation.",
    sector: "F&B / Entertainment",
    year: "2023",
    challenge:
      "Chatterbox needed a launch campaign that would cut through the noise of a saturated F&B market. The brief was simple: make people talk. The challenge was doing that authentically without relying on paid reach.",
    strategy:
      "We identified a cultural tension point — everyone has opinions about where to eat, but nobody captures those moments. We built a campaign around the idea of 'the conversation that starts at the table.' Authentic, unscripted, relatable.",
    execution:
      "The campaign launched across Instagram and TikTok simultaneously with a series of 15-45 second videos featuring real conversations — humor, debates, recommendations. We used a creator seeding strategy to amplify organic content without it feeling like an ad.",
    results:
      "The campaign generated 3.9M+ views within 30 days. It trended locally, generated hundreds of user-generated responses, and established Chatterbox as the most talked-about F&B brand in the market that quarter.",
    metrics: [
      { value: "3.9M+", label: "Views in 30 Days" },
      { value: "30", label: "Days to Result" },
      { value: "#1", label: "Trending Locally" },
      { value: "500+", label: "UGC Responses" },
    ],
    tags: ["Campaign Strategy", "Viral Content", "Creator Strategy", "F&B"],
    featured: true,
    color: "#8b7355",
  },
  {
    slug: "drseema-healthcare",
    brand: "Dr Seema",
    title: "Building Healthcare Authority Through Content",
    tagline: "Making medical expertise accessible, trustworthy, and shareable.",
    sector: "Healthcare",
    year: "2022",
    challenge:
      "Healthcare content is notoriously difficult — too clinical and you lose the audience, too casual and you lose credibility. Dr Seema needed a content presence that positioned her as the trusted expert while remaining accessible.",
    strategy:
      "We developed an 'expert simplification' framework — taking complex medical topics and creating content that educated without condescending. The strategy prioritized trust-building content that demonstrated expertise through clarity.",
    execution:
      "We created a mixed content format: long-form educational videos, short myth-busting Reels, and patient story narratives (with permission). Each piece was carefully crafted to feel personal, not institutional.",
    results:
      "Dr Seema's digital presence transformed from zero to a trusted voice in healthcare content. Patient inquiries from social media increased significantly, and her content began being shared by other medical professionals.",
    metrics: [
      { value: "10x", label: "Audience Growth" },
      { value: "65%", label: "Reach Increase" },
      { value: "200%", label: "Inquiry Growth" },
      { value: "12", label: "Months Strategy" },
    ],
    tags: ["Healthcare", "Brand Authority", "Educational Content", "Trust Building"],
    featured: false,
    color: "#7a9e87",
  },
  {
    slug: "fabio-media-growth",
    brand: "Fabio Magazine",
    title: "3.3M Reach — Reinventing a Magazine for the Digital Age",
    tagline: "Editorial excellence meets digital strategy.",
    sector: "Media / Publishing",
    year: "2023",
    challenge:
      "Fabio Magazine had a strong print identity but struggled to translate its editorial quality to digital platforms. The content felt like scanned magazine pages rather than native digital experiences.",
    strategy:
      "We developed a 'digital-native editorial' approach — treating each post as its own piece of digital art while maintaining the magazine's premium aesthetic. Content was designed for screens first, not repurposed from print.",
    execution:
      "We redesigned the content pipeline: cover shoots became multi-asset digital campaigns, interviews became episodic video series, and features became interactive carousel experiences. A weekly publishing cadence was established with consistent visual identity.",
    results:
      "Fabio Magazine reached 3.3M organic users, grew its engaged community significantly, and became the reference publication for premium lifestyle content in the market. Monthly comments exceeded 2,000 — a testament to real community engagement.",
    metrics: [
      { value: "3.3M+", label: "Organic Reach" },
      { value: "2K+", label: "Monthly Comments" },
      { value: "400%", label: "Engagement Rate" },
      { value: "6", label: "Months Transformation" },
    ],
    tags: ["Media Strategy", "Editorial Content", "Digital Transformation", "Publishing"],
    featured: true,
    color: "#9b8b7a",
  },
];

export interface PortfolioItem {
  id: string;
  type: "image" | "video";
  publicId: string; // Cloudinary public ID — replace with your actual IDs
  title: string;
  category: string;
  aspect: "square" | "portrait" | "landscape";
}

export const portfolioItems: PortfolioItem[] = [
  { id: "1", type: "image" as const, publicId: "9_ofw11s", title: "level 2", category: "level 2", aspect: "square" as const },
  { id: "2", type: "image" as const, publicId: "8_m8desb", title: "level 2", category: "level 2", aspect: "square" as const },
  { id: "3", type: "image" as const, publicId: "7_noxwiw", title: "level 2", category: "level 2", aspect: "square" as const },
  { id: "4", type: "image" as const, publicId: "6_g0avkq", title: "level 2", category: "level 2", aspect: "portrait" as const },
  { id: "5", type: "image" as const, publicId: "5_ryq5kh", title: "level 2", category: "level 2", aspect: "square" as const },
  { id: "6", type: "image" as const, publicId: "4_fevebt", title: "level 2", category: "level 2", aspect: "square" as const },
  { id: "7", type: "image" as const, publicId: "30_mvkmrm", title: "level 2", category: "level 2", aspect: "square" as const },
  { id: "8", type: "image" as const, publicId: "3_k6e8ei", title: "level 2", category: "level 2", aspect: "portrait" as const },
  { id: "9", type: "image" as const, publicId: "2_cpwv2h", title: "level 2", category: "level 2", aspect: "portrait" as const },
  { id: "10", type: "image" as const, publicId: "10_jhkoi9", title: "level 2", category: "level 2", aspect: "square" as const },
  { id: "11", type: "image" as const, publicId: "1_oaiuyr", title: "level 2", category: "level 2", aspect: "portrait" as const },
  { id: "12", type: "image" as const, publicId: "05_ndyfdg", title: "level 2", category: "level 2", aspect: "square" as const },
  { id: "13", type: "image" as const, publicId: "04_ybrdnz", title: "level 2", category: "level 2", aspect: "square" as const },
  { id: "14", type: "image" as const, publicId: "03_wbkatj", title: "level 2", category: "level 2", aspect: "square" as const },
  { id: "15", type: "image" as const, publicId: "02_tiwid4", title: "level 2", category: "level 2", aspect: "square" as const },
  { id: "16", type: "image" as const, publicId: "01_vh2vvh", title: "level 2", category: "level 2", aspect: "square" as const },
  { id: "17", type: "image" as const, publicId: "0_l9qnvo", title: "level 2", category: "level 2", aspect: "portrait" as const },
  { id: "18", type: "video" as const, publicId: "9_azvdpe", title: "Klay", category: "Klay", aspect: "portrait" as const },
  { id: "19", type: "video" as const, publicId: "8_eynbjv", title: "Klay", category: "Klay", aspect: "portrait" as const },
  { id: "20", type: "video" as const, publicId: "7_hjaetd", title: "Klay", category: "Klay", aspect: "portrait" as const },
  { id: "21", type: "video" as const, publicId: "6_yhawsr", title: "Klay", category: "Klay", aspect: "portrait" as const },
  { id: "22", type: "video" as const, publicId: "5_so6v3n", title: "Klay", category: "Klay", aspect: "portrait" as const },
  { id: "23", type: "video" as const, publicId: "4_n1rkew", title: "Klay", category: "Klay", aspect: "portrait" as const },
  { id: "24", type: "video" as const, publicId: "3_fmohig", title: "Klay", category: "Klay", aspect: "portrait" as const },
  { id: "25", type: "video" as const, publicId: "2_g1x1qf", title: "Klay", category: "Klay", aspect: "portrait" as const },
  { id: "26", type: "video" as const, publicId: "11_jmsajt", title: "Klay", category: "Klay", aspect: "portrait" as const },
  { id: "27", type: "video" as const, publicId: "10_yhxjd9", title: "Klay", category: "Klay", aspect: "portrait" as const },
  { id: "28", type: "video" as const, publicId: "04_awcz29", title: "Klay", category: "Klay", aspect: "portrait" as const },
  { id: "29", type: "video" as const, publicId: "07_gjkqwy", title: "Klay", category: "Klay", aspect: "portrait" as const },
  { id: "30", type: "image" as const, publicId: "1_qzkpul", title: "Klay", category: "Klay", aspect: "square" as const },
  { id: "31", type: "video" as const, publicId: "01_jsy1dd", title: "Klay", category: "Klay", aspect: "portrait" as const },
  { id: "32", type: "video" as const, publicId: "06_tafvmq", title: "Klay", category: "Klay", aspect: "portrait" as const },
  { id: "33", type: "video" as const, publicId: "05_uaaavp", title: "Klay", category: "Klay", aspect: "portrait" as const },
  { id: "34", type: "video" as const, publicId: "03_b8apor", title: "Klay", category: "Klay", aspect: "portrait" as const },
  { id: "35", type: "video" as const, publicId: "02_w436te", title: "Klay", category: "Klay", aspect: "portrait" as const },
  { id: "36", type: "image" as const, publicId: "Artboard_1_uswt2l", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "37", type: "image" as const, publicId: "_MFF1411_v9ze4h", title: "Espresso", category: "Espresso", aspect: "portrait" as const },
  { id: "38", type: "image" as const, publicId: "9_aq8zr3", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "39", type: "image" as const, publicId: "8_lqojzg", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "40", type: "image" as const, publicId: "7_w7tlmv", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "41", type: "image" as const, publicId: "6_z0hkzk", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "42", type: "image" as const, publicId: "58_nso93c", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "43", type: "video" as const, publicId: "57_lfuo2z", title: "Espresso", category: "Espresso", aspect: "portrait" as const },
  { id: "44", type: "video" as const, publicId: "56_kscvo0", title: "Espresso", category: "Espresso", aspect: "portrait" as const },
  { id: "45", type: "video" as const, publicId: "54_wtqqvy", title: "Espresso", category: "Espresso", aspect: "portrait" as const },
  { id: "46", type: "video" as const, publicId: "55_ve9qbs", title: "Espresso", category: "Espresso", aspect: "portrait" as const },
  { id: "47", type: "image" as const, publicId: "53_c7lv0c", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "48", type: "image" as const, publicId: "52_hud2pw", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "49", type: "image" as const, publicId: "51_yvqwc8", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "50", type: "image" as const, publicId: "50_m5kpsi", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "51", type: "image" as const, publicId: "5_lhuchw", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "52", type: "image" as const, publicId: "49_sbenog", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "53", type: "image" as const, publicId: "48_p5hhw4", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "54", type: "image" as const, publicId: "47_jrexqd", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "55", type: "image" as const, publicId: "46_mbz37y", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "56", type: "image" as const, publicId: "45_po08sh", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "57", type: "image" as const, publicId: "44_z5rrkd", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "58", type: "image" as const, publicId: "43_xldhe4", title: "Espresso", category: "Espresso", aspect: "portrait" as const },
  { id: "59", type: "image" as const, publicId: "42_hpsu3u", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "60", type: "image" as const, publicId: "41_m43wf3", title: "Espresso", category: "Espresso", aspect: "portrait" as const },
  { id: "61", type: "image" as const, publicId: "40_tpaprq", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "62", type: "image" as const, publicId: "4_zbnjhy", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "63", type: "image" as const, publicId: "39_ebdoo9", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "64", type: "image" as const, publicId: "38_rpwckd", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "65", type: "image" as const, publicId: "3_luzo2f", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "66", type: "image" as const, publicId: "37_fqvrdu", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "67", type: "image" as const, publicId: "36_imcmrt", title: "Espresso", category: "Espresso", aspect: "portrait" as const },
  { id: "68", type: "image" as const, publicId: "35_xrzygo", title: "Espresso", category: "Espresso", aspect: "portrait" as const },
  { id: "69", type: "image" as const, publicId: "34_auidbp", title: "Espresso", category: "Espresso", aspect: "portrait" as const },
  { id: "70", type: "image" as const, publicId: "33_l1op6b", title: "Espresso", category: "Espresso", aspect: "portrait" as const },
  { id: "71", type: "image" as const, publicId: "32_k7438y", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "72", type: "image" as const, publicId: "31_hcohda", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "73", type: "image" as const, publicId: "30_ztm9xq", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "74", type: "image" as const, publicId: "3_i1gmqu", title: "Espresso", category: "Espresso", aspect: "portrait" as const },
  { id: "75", type: "image" as const, publicId: "29_caf0i7", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "76", type: "image" as const, publicId: "28_roniys", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "77", type: "image" as const, publicId: "27_lhgksb", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "78", type: "image" as const, publicId: "26_xhbgzq", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "79", type: "image" as const, publicId: "25_yktnjr", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "80", type: "image" as const, publicId: "24_rfhnon", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "81", type: "image" as const, publicId: "23_uk202g", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "82", type: "image" as const, publicId: "22_lnhs7z", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "83", type: "image" as const, publicId: "20_iw97ov", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "84", type: "image" as const, publicId: "21_mo7o6z", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "85", type: "image" as const, publicId: "2_uk34mo", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "86", type: "image" as const, publicId: "2_nlcwzc", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "87", type: "image" as const, publicId: "19_btxooc", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "88", type: "image" as const, publicId: "16_zkiwml", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "89", type: "image" as const, publicId: "18_utjs0q", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "90", type: "image" as const, publicId: "17_m5n3o9", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "91", type: "image" as const, publicId: "15_jgfsyd", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "92", type: "image" as const, publicId: "14_ezcnix", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "93", type: "image" as const, publicId: "13_ikwbso", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "94", type: "image" as const, publicId: "11_r19tft", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "95", type: "image" as const, publicId: "12_qxldqm", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "96", type: "image" as const, publicId: "1_umzhkd", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "97", type: "video" as const, publicId: "040_kpdeji", title: "Espresso", category: "Espresso", aspect: "portrait" as const },
  { id: "98", type: "image" as const, publicId: "10_i9gbdm", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "99", type: "image" as const, publicId: "0_yx4swd", title: "Espresso", category: "Espresso", aspect: "square" as const },
  { id: "171", type: "video" as const, publicId: "Kolapurix3_cbu34q", title: "Sulafah", category: "Sulafah", aspect: "portrait" as const },
  { id: "172", type: "video" as const, publicId: "reel_1_ohou9x", title: "Sulafah", category: "Sulafah", aspect: "portrait" as const },
  { id: "173", type: "video" as const, publicId: "gold-stones_r9u6zu", title: "Sulafah", category: "Sulafah", aspect: "portrait" as const },
  { id: "174", type: "image" as const, publicId: "9_vnj0xx", title: "Sulafah", category: "Sulafah", aspect: "landscape" as const },
  { id: "175", type: "image" as const, publicId: "8_iah9pk", title: "Sulafah", category: "Sulafah", aspect: "square" as const },
  { id: "176", type: "image" as const, publicId: "7_ogtwmh", title: "Sulafah", category: "Sulafah", aspect: "square" as const },
  { id: "177", type: "video" as const, publicId: "33_bg4gi7", title: "Sulafah", category: "Sulafah", aspect: "portrait" as const },
  { id: "178", type: "image" as const, publicId: "6_tccccs", title: "Sulafah", category: "Sulafah", aspect: "square" as const },
  { id: "179", type: "video" as const, publicId: "34_ouvruv", title: "Sulafah", category: "Sulafah", aspect: "portrait" as const },
  { id: "180", type: "video" as const, publicId: "32_dt9otq", title: "Sulafah", category: "Sulafah", aspect: "portrait" as const },
  { id: "181", type: "image" as const, publicId: "5_lxepre", title: "Sulafah", category: "Sulafah", aspect: "square" as const },
  { id: "182", type: "video" as const, publicId: "31_g0pp7f", title: "Sulafah", category: "Sulafah", aspect: "portrait" as const },
  { id: "183", type: "video" as const, publicId: "30_komsgj", title: "Sulafah", category: "Sulafah", aspect: "portrait" as const },
  { id: "184", type: "image" as const, publicId: "4_h2huk2", title: "Sulafah", category: "Sulafah", aspect: "square" as const },
  { id: "185", type: "image" as const, publicId: "29_o3h7l6", title: "Sulafah", category: "Sulafah", aspect: "square" as const },
  { id: "186", type: "image" as const, publicId: "3_mgxndu", title: "Sulafah", category: "Sulafah", aspect: "square" as const },
  { id: "187", type: "image" as const, publicId: "28_dcwion", title: "Sulafah", category: "Sulafah", aspect: "square" as const },
  { id: "188", type: "image" as const, publicId: "27_crlpnw", title: "Sulafah", category: "Sulafah", aspect: "square" as const },
  { id: "189", type: "image" as const, publicId: "21_qkcmi0", title: "Sulafah", category: "Sulafah", aspect: "square" as const },
  { id: "190", type: "image" as const, publicId: "26_uyalma", title: "Sulafah", category: "Sulafah", aspect: "square" as const },
  { id: "191", type: "image" as const, publicId: "23_lkp5vx", title: "Sulafah", category: "Sulafah", aspect: "square" as const },
  { id: "192", type: "image" as const, publicId: "22_qvow70", title: "Sulafah", category: "Sulafah", aspect: "square" as const },
  { id: "193", type: "image" as const, publicId: "25_d5kqfe", title: "Sulafah", category: "Sulafah", aspect: "square" as const },
  { id: "194", type: "image" as const, publicId: "24_ptvk01", title: "Sulafah", category: "Sulafah", aspect: "square" as const },
  { id: "195", type: "image" as const, publicId: "20_h3unic", title: "Sulafah", category: "Sulafah", aspect: "square" as const },
  { id: "196", type: "image" as const, publicId: "19_hogop4", title: "Sulafah", category: "Sulafah", aspect: "square" as const },
  { id: "197", type: "image" as const, publicId: "18_nnilsa", title: "Sulafah", category: "Sulafah", aspect: "square" as const },
  { id: "198", type: "image" as const, publicId: "2_agfdbw", title: "Sulafah", category: "Sulafah", aspect: "square" as const },
  { id: "199", type: "image" as const, publicId: "17_wpuzqz", title: "Sulafah", category: "Sulafah", aspect: "square" as const },
  { id: "200", type: "image" as const, publicId: "16_wnsbm5", title: "Sulafah", category: "Sulafah", aspect: "square" as const },
  { id: "201", type: "image" as const, publicId: "15_pjvdp9", title: "Sulafah", category: "Sulafah", aspect: "square" as const },
  { id: "202", type: "image" as const, publicId: "14_ca0sbe", title: "Sulafah", category: "Sulafah", aspect: "square" as const },
  { id: "203", type: "image" as const, publicId: "12_uoxcyl", title: "Sulafah", category: "Sulafah", aspect: "square" as const },
  { id: "204", type: "image" as const, publicId: "13_g7eyps", title: "Sulafah", category: "Sulafah", aspect: "square" as const },
  { id: "205", type: "image" as const, publicId: "11_g4khql", title: "Sulafah", category: "Sulafah", aspect: "square" as const },
  { id: "206", type: "image" as const, publicId: "10_qqhmro", title: "Sulafah", category: "Sulafah", aspect: "square" as const },
  { id: "207", type: "image" as const, publicId: "1_cwmvz5", title: "Sulafah", category: "Sulafah", aspect: "square" as const },
  { id: "208", type: "video" as const, publicId: "5_cykrz9", title: "PITS", category: "PITS", aspect: "portrait" as const },
  { id: "209", type: "image" as const, publicId: "4_iygicd", title: "PITS", category: "PITS", aspect: "square" as const },
  { id: "210", type: "image" as const, publicId: "7_eozvgq", title: "PITS", category: "PITS", aspect: "square" as const },
  { id: "211", type: "image" as const, publicId: "9_lp5dly", title: "PITS", category: "PITS", aspect: "square" as const },
  { id: "212", type: "image" as const, publicId: "8_kqar98", title: "PITS", category: "PITS", aspect: "square" as const },
  { id: "213", type: "image" as const, publicId: "6_avv7ei", title: "PITS", category: "PITS", aspect: "square" as const },
  { id: "214", type: "image" as const, publicId: "5_u29q4l", title: "PITS", category: "PITS", aspect: "square" as const },
  { id: "215", type: "video" as const, publicId: "04_k07cvo", title: "PITS", category: "PITS", aspect: "portrait" as const },
  { id: "216", type: "image" as const, publicId: "3_aglkjd", title: "PITS", category: "PITS", aspect: "square" as const },
  { id: "217", type: "video" as const, publicId: "03_fhdswz", title: "PITS", category: "PITS", aspect: "portrait" as const },
  { id: "218", type: "video" as const, publicId: "025_ycjvs7", title: "PITS", category: "PITS", aspect: "portrait" as const },
  { id: "219", type: "image" as const, publicId: "2_u8ohh1", title: "PITS", category: "PITS", aspect: "square" as const },
  { id: "220", type: "image" as const, publicId: "20_nywblx", title: "PITS", category: "PITS", aspect: "square" as const },
  { id: "221", type: "image" as const, publicId: "1_va8lio", title: "PITS", category: "PITS", aspect: "square" as const },
  { id: "222", type: "video" as const, publicId: "014_xlorlv", title: "PITS", category: "PITS", aspect: "portrait" as const },
  { id: "223", type: "image" as const, publicId: "02_khk4do", title: "PITS", category: "PITS", aspect: "square" as const },
  { id: "224", type: "image" as const, publicId: "032_a7fvn5", title: "PITS", category: "PITS", aspect: "square" as const },
  { id: "225", type: "image" as const, publicId: "0000000025_kpnuap", title: "PITS", category: "PITS", aspect: "square" as const },
  { id: "226", type: "image" as const, publicId: "01_wmbppv", title: "PITS", category: "PITS", aspect: "square" as const },
  { id: "227", type: "image" as const, publicId: "0_hboa0y", title: "PITS", category: "PITS", aspect: "square" as const },
  { id: "228", type: "image" as const, publicId: "00_yuxzar", title: "PITS", category: "PITS", aspect: "square" as const },
  { id: "229", type: "video" as const, publicId: "6_n8g6ql", title: "Manas", category: "Manas", aspect: "portrait" as const },
  { id: "230", type: "video" as const, publicId: "7_ycnczs", title: "Manas", category: "Manas", aspect: "portrait" as const },
  { id: "231", type: "video" as const, publicId: "5_czlajq", title: "Manas", category: "Manas", aspect: "portrait" as const },
  { id: "232", type: "video" as const, publicId: "44_klcvwx", title: "Manas", category: "Manas", aspect: "portrait" as const },
  { id: "233", type: "image" as const, publicId: "9_dqbfut", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "234", type: "image" as const, publicId: "8_eiuigp", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "235", type: "video" as const, publicId: "45_xnppac", title: "Manas", category: "Manas", aspect: "portrait" as const },
  { id: "236", type: "video" as const, publicId: "4_y6sfbn", title: "Manas", category: "Manas", aspect: "portrait" as const },
  { id: "237", type: "image" as const, publicId: "7_hlq34q", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "238", type: "image" as const, publicId: "6_q9fzzg", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "239", type: "image" as const, publicId: "5_vosncc", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "240", type: "image" as const, publicId: "43_ddjokg", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "241", type: "image" as const, publicId: "42_sqydvb", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "242", type: "image" as const, publicId: "41_bcbyxr", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "243", type: "image" as const, publicId: "40_ldgurs", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "244", type: "image" as const, publicId: "4_blkt8n", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "245", type: "image" as const, publicId: "39_irfhjd", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "246", type: "video" as const, publicId: "3_kd0iw1", title: "Manas", category: "Manas", aspect: "portrait" as const },
  { id: "247", type: "image" as const, publicId: "38_ewjo2r", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "248", type: "image" as const, publicId: "37_bfmzzn", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "249", type: "image" as const, publicId: "374_rx1ovp", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "250", type: "image" as const, publicId: "32_ikrwmy", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "251", type: "image" as const, publicId: "36_ddltdi", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "252", type: "image" as const, publicId: "35_ocd4jg", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "253", type: "image" as const, publicId: "29_unmxt6", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "254", type: "image" as const, publicId: "33_wwvpfr", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "255", type: "image" as const, publicId: "25_rcnej4", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "256", type: "image" as const, publicId: "22_rthlnn", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "257", type: "image" as const, publicId: "30_ygeusw", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "258", type: "image" as const, publicId: "3_b63jwr", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "259", type: "image" as const, publicId: "27_stip20", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "260", type: "image" as const, publicId: "26_uokm6y", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "261", type: "image" as const, publicId: "28_bajhcw", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "262", type: "image" as const, publicId: "24_iwvptn", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "263", type: "image" as const, publicId: "23_m3ofqf", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "264", type: "image" as const, publicId: "21_foerva", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "265", type: "image" as const, publicId: "18_tjlk8s", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "266", type: "image" as const, publicId: "20_q3zqc7", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "267", type: "video" as const, publicId: "2_oe64sq", title: "Manas", category: "Manas", aspect: "portrait" as const },
  { id: "268", type: "image" as const, publicId: "19_kdekys", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "269", type: "image" as const, publicId: "2_i9suh4", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "270", type: "video" as const, publicId: "1_b8kf1b", title: "Manas", category: "Manas", aspect: "portrait" as const },
  { id: "271", type: "image" as const, publicId: "17_a0vpbl", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "272", type: "image" as const, publicId: "16_rlbocv", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "273", type: "image" as const, publicId: "11_av3efv", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "274", type: "image" as const, publicId: "09_ohrif2", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "275", type: "image" as const, publicId: "15_qujvpm", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "276", type: "image" as const, publicId: "14_qj8tyg", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "277", type: "image" as const, publicId: "13_ap032e", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "278", type: "image" as const, publicId: "12_luk2cn", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "279", type: "image" as const, publicId: "101_vg8oi4", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "280", type: "image" as const, publicId: "06_bcbu5c", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "281", type: "image" as const, publicId: "10_m4akuj", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "282", type: "image" as const, publicId: "1_j2ppaj", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "283", type: "image" as const, publicId: "08_f4jk2z", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "284", type: "image" as const, publicId: "04_akvrnh", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "285", type: "image" as const, publicId: "07_jrp8mq", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "286", type: "image" as const, publicId: "03_ze0qxf", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "287", type: "image" as const, publicId: "05_yeydcp", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "288", type: "image" as const, publicId: "02_orlvdj", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "289", type: "image" as const, publicId: "020_dslbwn", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "290", type: "image" as const, publicId: "01_drajlh", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "291", type: "image" as const, publicId: "00_ngqpjp", title: "Manas", category: "Manas", aspect: "square" as const },
  { id: "292", type: "image" as const, publicId: "0_tpce3b", title: "Manas", category: "Manas", aspect: "square" as const },
];

export const timelineItems = [
  {
    year: "2024",
    title: "Multi-Brand Growth Architecture",
    description: "Led simultaneous growth campaigns across 5+ brands, developing scalable content systems and campaign architecture that consistently delivered millions in organic reach.",
  },
  {
    year: "2023",
    title: "Viral Campaign Execution",
    description: "Designed and executed multiple campaigns including Chatterbox's 3.9M view viral campaign and Espresso's 5.2M view content ecosystem.",
  },
  {
    year: "2022",
    title: "Healthcare & Corporate Strategy",
    description: "Expanded into healthcare and corporate sectors, developing trust-based content frameworks for Dr Seema and corporate brand positioning for AFM.",
  },
  {
    year: "2020",
    title: "Fashion & Lifestyle Focus",
    description: "Established expertise in fashion content strategy, working with Shahid Afridi Clothing and building community-first brand audiences in the fashion sector.",
  },
];
